// Curated tiered keyword list. Each preset is tagged with the mode it belongs
// to: 'leadgen' (Ventix ICP) or 'ecom' (Shopify brand finder). The UI shows the
// presets matching the currently selected mode.
export const KEYWORD_PRESETS = [
  {
    id: 'realestate-core',
    mode: 'leadgen',
    label: 'Real estate — primary ICP',
    tier: 1,
    description: 'Realtors, brokerages, buyer/seller funnels. Run with ad category = Properties.',
    recommendedCategory: 'housing_ads',
    keywords: [
      'real estate',
      'realtor',
      'real estate agent',
      'real estate broker',
      'real estate brokerage',
      'homes for sale',
      'houses for sale',
      'luxury homes',
      'luxury real estate',
      'new homes for sale',
      'new construction homes',
      'first time home buyer',
      'home valuation',
      'free home valuation',
      'sell your house',
      'sell your home',
      'list your home',
    ],
  },
  {
    id: 'cash-buyers',
    mode: 'leadgen',
    label: 'Cash buyers / investors',
    tier: 2,
    description: 'Outbound seller acquisition use case (demo.ventixai.com).',
    recommendedCategory: 'housing_ads',
    keywords: [
      'we buy houses',
      'cash for houses',
      'cash home buyer',
      'sell my house fast',
      'sell house fast',
      'i buy houses',
      'cash offer for your home',
      'real estate investor',
      'investment property',
      'house flipping',
      'fix and flip',
      'wholesale real estate',
      'motivated seller',
    ],
  },
  {
    id: 'mortgage',
    mode: 'leadgen',
    label: 'Mortgage / home finance',
    tier: 3,
    description: 'Same lead pool, same pain. Run with ad category = Financial products and services.',
    recommendedCategory: 'credit_ads',
    keywords: [
      'mortgage broker',
      'mortgage rates',
      'home loan',
      'refinance my home',
      'mortgage refinance',
      'pre approved mortgage',
      'first time home buyer loan',
      'FHA loan',
      'VA loan',
    ],
  },
  {
    id: 'mena',
    mode: 'leadgen',
    label: 'MENA real estate',
    tier: 4,
    description: 'Pair with UAE / Saudi / Egypt / Qatar locations.',
    recommendedCategory: 'housing_ads',
    keywords: [
      'off plan property',
      'off plan Dubai',
      'Dubai property',
      'Dubai real estate',
      'Dubai apartments',
      'apartment for sale',
      'villa for sale',
      'Abu Dhabi property',
      'Riyadh real estate',
      'payment plan property',
    ],
  },
  {
    id: 'adjacent',
    mode: 'leadgen',
    label: 'Adjacent verticals',
    tier: 5,
    description: 'Solar, roofing, insurance, legal, dental, funding, coaching.',
    recommendedCategory: 'all',
    keywords: [
      'solar panels',
      'solar quote',
      'roofing',
      'roof replacement',
      'HVAC installation',
      'life insurance quote',
      'final expense insurance',
      'medicare advantage',
      'personal injury lawyer',
      'car accident lawyer',
      'dental implants',
      'cosmetic dentistry',
      'business loan',
      'merchant cash advance',
      'business coach',
    ],
  },

  // ── Ecom brand-finder presets ──────────────────────────────────────────────
  {
    id: 'ecom-fashion',
    mode: 'ecom',
    label: 'Fashion & apparel',
    tier: 1,
    description: 'Clothing, footwear, accessories brands.',
    recommendedCategory: 'all',
    keywords: [
      'clothing brand', 'streetwear', 'activewear', 'swimwear', 'dresses',
      'sneakers', 'handbags', 'sunglasses', 'jewelry', 'watches',
    ],
  },
  {
    id: 'ecom-beauty',
    mode: 'ecom',
    label: 'Beauty & skincare',
    tier: 2,
    description: 'Cosmetics, skincare, haircare, supplements.',
    recommendedCategory: 'all',
    keywords: [
      'skincare', 'serum', 'moisturizer', 'makeup', 'cosmetics',
      'haircare', 'hair growth', 'supplements', 'collagen', 'vitamins',
    ],
  },
  {
    id: 'ecom-home',
    mode: 'ecom',
    label: 'Home & lifestyle',
    tier: 3,
    description: 'Furniture, home decor, kitchen, pet, gadgets.',
    recommendedCategory: 'all',
    keywords: [
      'home decor', 'furniture', 'bedding', 'kitchenware', 'candles',
      'pet supplies', 'gadgets', 'tech accessories', 'water bottle', 'coffee',
    ],
  },
];
